Refactor linkdot, add rm from manifest

diff --git a/bin/link_dot_to_home b/bin/link_dot_to_home
--- a/bin/link_dot_to_home
+++ b/bin/link_dot_to_home
@@ -4,6 +4,7 @@ TILDE_DIR="$HOME/.tilde"
 MANIFEST_DIR="$HOME/.tilde/manifests"
 REPO_DIR="$HOME/.tilde/repos"
 BASENAME=$1
+THIS_REPO="$REPO_DIR/$BASENAME"
 
 BAD_FILES=". .. .git .gitignore .mrconfig .svn"
 
@@ -13,13 +14,13 @@ if [ -e $manifest ]; then
 	exit
 fi
 
-if [ ! -d "$REPO_DIR/$BASENAME" ]; then
-	echo "E: Couldn't find directory $REPO_DIR/$BASENAME"
+if [ ! -d "$THIS_REPO" ]; then
+	echo "E: Couldn't find directory $THIS_REPO"
 	exit
 fi
 
 to_link=()
-for file in "$REPO_DIR/$BASENAME"/.*; do 
+for file in "$THIS_REPO"/.*; do 
 	base_file=$(basename $file)
 	# Check to make sure the filename isn't in the exclude list
 	bad=""; 
@@ -41,8 +42,14 @@ for file in "$REPO_DIR/$BASENAME"/.*; do
 		echo "E: Found matching $base_file in manifest $matching_manifest, aborting"
 		exit 2
 	fi
+
+	if [ -e "$HOME/$base_file" -o -L "$HOME/$base_file" ]; then
+		echo "E: Found $base_file already existing in home. Aborting"
+		exit 2
+	fi
 done
 for linker in ${to_link[@]}; do
-	echo ln -s $linker $HOME
+	set -o nounset
+	ln -s "$THIS_REPO/$linker" $HOME
 	echo "$linker" >> $manifest
 done
